### ISSUE TITLE
`spin test` fails in `meson install` if `PYTHONPATH` is already set

### ISSUE THREAD

**Issue by lagru** [scientific-python/spin#113]
## Desription

It seems that this line

https://github.com/scientific-python/spin/blob/8ddc0abea6221bcc6c0ade7ad86f9d1ad1d9b4d8/spin/cmds/meson.py#L32-L33

trips up something in the following build chain, that is not expecting `PYTHONPATH` to contain more than one PATH. It looks like it's happening after / inside `meson install` step, though if I run that exact command manually it seems to pass fine, so maybe it's not originating from there. 

## Way to reproduce

On Linux with the current `main` of spin (https://github.com/scientific-python/spin/commit/8ddc0abea6221bcc6c0ade7ad86f9d1ad1d9b4d8), [setup a development environmet for scikit-image](https://scikit-image.org/docs/dev/user_guide/install.html#build-environment-setup) and run

```sh
export PYTHONPATH=/home
spin test
```

Also reproduce-able on Windows it seems: https://discuss.scientific-python.org/t/spin-test-fails-on-windows/830

## Output

```sh
Invoking `build` prior to running tests:
$ meson compile -C build
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /home/lg/.local/lib/venv/skimagedev/bin/ninja -C /home/lg/Res/scikit-image/build
ninja: Entering directory `/home/lg/Res/scikit-image/build'
ninja: no work to do.
$ meson install --only-changed -C build --destdir ../build-install
$ export PYTHONPATH="/home/lg/Res/scikit-image/build-install/usr/lib/python3.11/site-packages"
$ /home/lg/.local/lib/venv/skimagedev/bin/python -P -c 'import skimage'
$ export PYTHONPATH="/home/lg/Res/scikit-image/build-install/usr/lib/python3.11/site-packages:/home"
$ cd /home/lg/Res/scikit-image/build-install/usr/lib/python3.11/site-packages:/home
[Errno 2] No such file or directory: '/home/lg/Res/scikit-image/build-install/usr/lib/python3.11/site-packages:/home'; aborting.
```

**Comment by bsipocz** [comment]
Thanks for opening this, I run into this one, too in one of the more recent attempts of getting numpy/scipy builds working again locally.
