### ISSUE TITLE
Question: Show compilation flag

### ISSUE THREAD

**Issue by skoudoro** [scientific-python/spin#116]
Hi Spin Team,

When I use `spin build -v`, I would like to display the compilation flags (like `clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniforge/base/envs/dipy-39-x86/include -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniforge/base/envs/dipy-39-x86/include -I/opt/homebrew/Caskroom/miniforge/base/envs/dipy-39-x86/include/python3.9 -c test.c -o test.o -msse2 -mfpmath=sse `)

but currently, it is hidden. 

is there a way to do that? What do I miss? 

Thank you for your feedback

**Comment by stefanv** [comment]
Thanks for the report @skoudoro. I've made a PR to address your concern.

**Comment by skoudoro** [comment]
Thank you for this !

looking forward for the future minor release. it will help me to understand some of my CI's in https://github.com/dipy/dipy/pull/2715. instead of doing it manually.

**Comment by stefanv** [comment]
Go ahead and try v0.6: https://github.com/scientific-python/spin/releases/tag/v0.6
