### ISSUE TITLE
Add `spin --version`

### ISSUE THREAD

**Issue by stefanv** [scientific-python/spin#123]

**Comment by marameref** [comment]
@stefanv pls i will need more context to this issue. Which file(s) do you want fixed and what is the description of the problem and expected solution. Thanks

**Comment by stefanv** [comment]
Thanks for your interest @marameref.

We need to:

(1) Add a `__version__` variable in `spin/__init__.py`
(2) Tell setuptools that the version needs to be obtained dynamically: https://github.com/networkx/networkx/blob/main/pyproject.toml#L10
(3) Tell setuptools where to read the version from: https://github.com/networkx/networkx/blob/main/pyproject.toml#L128
(4) Add a `version` command in `https://github.com/scientific-python/spin/blob/main/spin/cmds/__init__.py` that prints `spin.__version__`.

**Comment by marameref** [comment]
ok, am on it, but out of curiosity I would like to know if you will be the one to review and approve my PR when I am done. 

@stefanv

**Comment by jarrodmillman** [comment]
It will be me or @stefanv depending on who gets to it first. But we are in agreement about what needs to be done for this PR.
