### ISSUE TITLE
Create a `spin lldb` similar to `spin gdb`.

### ISSUE THREAD

**Issue by ngoldbaum** [scientific-python/spin#125]
Using `gdb` on a mac is an exercise in pain because of SIP and code signing. People will have a much easier time using `lldb` so if possible we should create a new `spin` subcommand for it.

**Comment by stefanv** [comment]
I can't test this on my machine, but I'd be happy to review.
Do you think we should make a generic `debug` command, or a specialized one for `lldb`?

**Comment by stefanv** [comment]
Actually, lldb is available on Linux.
