### ISSUE TITLE
Support alternate configuration file .spin.toml

### ISSUE THREAD

**Issue by dalcinl** [scientific-python/spin#128]
I would like to propose support for alternate configuration file names, let say `.spin.toml`, that would take precedence over `pyproject.toml` if present in the source tree. 

Would you guys accept a PR implementing this feature?

Rationale:

* Support using `spin` in projects that may not be strictly related to Python and where `pyproject.toml` would look awkward/confusing to have in the source tree.
* Prevent clutter in `pyproject.toml`. Some developers prefer to keep `pyproject.toml` as minimal as possible. So let's be open-minded and let users decide on base to their preferences.
* Follow other Python tools (`pytest`, `ruff`, `mypy`), even if they may be doing it for legacy reasons.

**Comment by stefanv** [comment]
Hi Lisandro, thanks for the feature suggestion. I think it's a good idea.

**Comment by stefanv** [comment]
For now, probably safest to error out if both the config file and a spin section in pyproject.toml are present.
