### ISSUE TITLE
Add `spin clean` and `spin help`

### ISSUE THREAD

**Issue by skoudoro** [scientific-python/spin#133]
Hi Spin Team,

it would be great to add:

- `spin clean`.   Sometimes, you just want to clean the build. But doing `spin build --clean` will still run a build which make sense. 
- `spin help`.  I have the bad habit to do this mistake and I am sure to not be the only one. I see it just as an alternative to `spin --help`. I think having both option will be convenient for multiple people

Feel free to close this issue if you think that adding those features is not valuable. 

Thanks !

**Comment by stefanv** [comment]
Hi @skoudoro. I've implemented the alias for `--help`.

For `clean`, the easiest is to add the following custom command:

```python
import click
import os
import shutil


build_dir = "build"
install_dir = "build-install"


@click.command()
def clean():
    print(f"Removing `{build_dir}`")
    if os.path.isdir(build_dir):
            shutil.rmtree(build_dir)
    print(f"Removing `{install_dir}`")
    if os.path.isdir(install_dir):
        shutil.rmtree(install_dir)
```

**Comment by skoudoro** [comment]
Thank you @stefanv
