### ISSUE TITLE
Is it possible to add a command for editable installs?

### ISSUE THREAD

**Issue by adam2392** [scientific-python/spin#138]
I find myself repeating this workflow often when switching between branches:

```
./spin build -j 6 --clean
pip install --no-build-isolation --editable .
```

It's quite annoying because I always have to google to make sure I'm writing this pip install editable command correctly. I'm wondering if it's sensible to package this into a single command, `install`, which has the editable flag by default. Since this is a "developer tool" package, I assume this is reasonable. 

Xref: https://meson-python.readthedocs.io/en/latest/how-to-guides/editable-installs.html

**Comment by stefanv** [comment]
That'd be great, Adam! Yes, how about we put it in `spin.cmds.pip.install`?
