### ISSUE TITLE
Files removed by `spin docs --clean` isn't configurable for meson

### ISSUE THREAD

**Issue by ngoldbaum** [scientific-python/spin#156]
It would be nice to specify more folders to remove here:

https://github.com/scientific-python/spin/blob/c32217e7b61446960cf7819c45eb26ed693054bc/spin/cmds/meson.py#L625-L631

ideally without copy/pasting the command into numpy's spin config.

**Comment by stefanv** [comment]
So, a configuration variable?

```
spin.build.dirty = [...]
```

**Comment by ngoldbaum** [comment]
For the docs build, yes. This is to handle generated docs from autosummary, which in my experience tends to end up in a `generated` folder in the docs source, and that path is going to be different from project to project.

**Comment by rgommers** [comment]
Seems reasonable to me. The expanding config in `pyproject.toml` is not ideal, so if this keeps happening it'd be nice to have this:

```toml
[tool.spin]
package = 'numpy'
config = '.spin/config.toml'
```

**Comment by stefanv** [comment]
We can add the ability to choose config names. Note that a spin-specific config is already supported.

**Comment by stefanv** [comment]
Another option is a more generic mechanism which allows you to override the default keyword arguments. That way you can send in options that are not supported by flags, but can be specified as function arguments (since spin is just a glorified function caller).

**Comment by rgommers** [comment]
> Note that a spin-specific config is already supported.

Ah, I missed that, thanks for pointing it out. It's this one line in the README: _Settings are stored in `.spin.toml`, `spin.toml`, or your project's `pyproject.toml`._

I kinda still like my suggestion: have an "entry point" in `pyproject.toml`, which then points at the actual place where the config is stored. The problem with fully separate files is discoverability; the problem with everything in `pyproject.toml` is that it quickly turns messy (e.g., in NumPy's `pyproject.toml`, the sections for `towncrier`, `cibuildwheel` and `spin` are all quite verbose).

Of course, the separate file could also simply be pointed to with a code comment in `pyproject.toml`, so probably we're fine as is.

**Comment by stefanv** [comment]
I'd be happy with having it as a configuration option too; whatever is useful :)
