### ISSUE TITLE
DOC,ENH: lldb/gdb option for test running

### ISSUE THREAD

**Issue by seberg** [scientific-python/spin#167]
I quite often need lldb/gdb not to hunt down a user issue but rather to hunt down issues that the test suite already catches (due to code changes).

`spin lldb -- python -mspin test` works fine, it feels a bit creative but maybe the path would be to just mention that possibility (since it isn't really that great to overload either command with options of the other).

**Comment by stefanv** [comment]
How about we add `spin lldb -t` as an alias for that?

**Comment by seberg** [comment]
Sounds good, would `-t testname` also work, or `-- test opts`?  (I think the first is mainly interesting, beyond that maybe the long form is just fine)

**Comment by stefanv** [comment]
Did you want the srgs to be passed to spin test, or to pytest?

**Comment by seberg** [comment]
Maybe?  I think most of the time only picking a test matters, so `-t` possibly followed after a test is sufficient.

**Comment by stefanv** [comment]
I see you already identified the basic problem with adding this option; if I add it to `test`, then we lose the `lldb` options, if I add it to `lldb`, we lose the test options.

For now, I added a line in the docs, https://github.com/scientific-python/spin/pull/170, but if you have other ideas of how to make it easier to launch tests under lldb, I'd be happy to take a pass at it.

**Comment by stefanv** [comment]
Closing for now as having been documented; since we haven't come up with a general design, a custom function for NumPy would also do the trick.
