### ISSUE TITLE
spin 0.8 in conda-forge?

### ISSUE THREAD

**Issue by melissawm** [scientific-python/spin#172]
It looks like spin 0.8 is not available in conda-forge. I found https://github.com/conda-forge/spin-feedstock/pull/6 and maybe it's just about pushing this button? 😄 

This issue came up because currently `spin docs` fails for NumPy if you are using conda instead of pip. Upgrading manually to spin 0.8 fixes the build.

**Comment by stefanv** [comment]
Resolved in https://github.com/conda-forge/spin-feedstock/pull/6
