### ISSUE TITLE
Document how to build the example package

### ISSUE THREAD

**Issue by Kai-Striega** [scientific-python/spin#174]
Hi all,

I'm currently trying to debug setting up spin for NumPy-Financial. I'm having some trouble with this. To start to debug I thought I would try to build the example in this repo (as NumPy-Financial is structured very similarly) however I'm unable to run `spin` in the project repo.

What I've done so far:

1. cloned the repo
2. created a virtual environment (``python - m venv .venv``)
3. activated the virtaul environment (``source .venv/bin/activate``)
4. installed the dependencies from the ``pyproject.toml`` file (``pip install .``)
5. tried to call the help function (``spin --help``)

The error I receive is:
```
(.venv) kai@kai-MS-7D32:~/Projects/spin$ spin --help
Error: needs valid configuration in [.spin.toml], [spin.toml] or [pyproject.toml]
```

The fix that I think would be appropriate is to document somewhere how to build the example package

**Comment by Kai-Striega** [comment]
I figured it out, you need to be in the ``example_pkg`` directory. 

Sorry for the noise!

**Comment by stefanv** [comment]
Glad you figured it out; don't hesitate to let us know if things are unclear.
