### ISSUE TITLE
Add types ? 

### ISSUE THREAD

**Issue by Carreau** [scientific-python/spin#177]
I just found an issue in numpy's usage of spins that would have been caught by types, 
but as spin does not seem to have types (and the `py.typed` marker), mypy just stop inferring.

**Comment by stefanv** [comment]
I wouldn't mind having types.

Just out of curiosity, what is the error that would have been caught?

**Comment by Carreau** [comment]
https://github.com/numpy/numpy/pull/26304, there was a migration from subprocess.run to  spin.utils.run and the usage of the return value of spin.util.run was improper when the subprocess would fail.

**Comment by stefanv** [comment]
Types scaffolding has been put in place with #188. I was going to add a `py.typed` file, but after some headscratching this does not seem to pertain to our situation (we don't provide any data structures that other libraries need)? But, happy to be corrected; I have a branch with it set up.

From here, we can continue typing the rest of `spin`.
