### ISSUE TITLE
Add test for #183

### ISSUE THREAD

**Issue by stefanv** [scientific-python/spin#184]
Failure without gcov

**Comment by vxst** [comment]
Shall I inject ctx.invoke? What's your recommendation on testing not passing gcov to build_cmd?

**Comment by stefanv** [comment]
Ah, right, this is because NumPy's custom build command doesn't have the same signature as the built-in build command. That's probably something that has to be addressed on the NumPy side, so it's OK to leave it "untested". We should have some freedom to change internal command APIs across versions.

**Comment by vxst** [comment]
Relying on strange things happens on a big project. I'll see whether it's possible to fix it on numpy side when I got time. :-)

**Comment by stefanv** [comment]
Thank you!
