### ISSUE TITLE
spin 0.9 update causes AttributeError in numpy CI

### ISSUE THREAD

**Issue by ngoldbaum** [scientific-python/spin#193]
It looks like this broke one of the numpy CI jobs: https://github.com/numpy/numpy/actions/runs/9087080853/job/24974107681?pr=26436

```
Error: 'types.SimpleNamespace' object has no attribute 'dir_info'; aborting.
```

And indeed there's a new access of a `dir_info` attribute added in #155.

Clues about how to fix this in the numpy CI would be appreciated if this isn't a spin bug.

**Comment by stefanv** [comment]
I can replicate with a conda install.

**Comment by asmeurer** [comment]
This error breaks numpy builds in a particularly confusing way. It doesn't help that Googling the error message doesn't lead to this issue for some reason (I guess Google doesn't actually index the web anymore). 

Is it possible for spin to output a traceback in cases like this? Perhaps whatever code is hiding the tracebacks could try to detect if the error is a spin internal error and unhide it in that case. 

To be clear if anyone does manage to find this issue, downgrading to spin=0.8 fixes the issue.

**Comment by stefanv** [comment]
Thanks, Aaron, I think that'd be a good feature to add.

NumPy CI is pinned to the hash which works, but we should get 0.9.1 out the door.

**Comment by stefanv** [comment]
See https://github.com/scientific-python/spin/pull/198
