### ISSUE TITLE
spin catches SIGINT and send SIGTERM to subprocess

### ISSUE THREAD

**Issue by adrinjalali** [scientific-python/spin#235]
Seems like `spin` is sending a `SIGTERM` (or `SIGKILL`?)signal to the underlying process when it receives a `SIGINT`, which seems odd when working in a `spin run python -i /path/to/script.py` kinda command.

Shouldn't spin forward a `SIGINT` instead? while running the process in `python`, I wouldn't expect `CTRL+C` to exit the process really.

**Comment by stefanv** [comment]
Hrm, we're not supposed to be sending anything special; I can take a look.

**Comment by stefanv** [comment]
Looks like an interaction with `subprocess.run`; investigating further.
