### ISSUE TITLE
0.13 release?

### ISSUE THREAD

**Issue by ngoldbaum** [scientific-python/spin#245]
Is it OK to publish the current state of the `main` branch to pypi? After that I'd like to try updating NumPy's meson config to fully match the upstream API as it exists right now before trying to think about https://github.com/scientific-python/spin/issues/242 (would still like your thoughts there, I'm not sure if it requires doing a breaking change or not).

NumPy currently has spin 0.8 in its `build_requirements.txt` and I'd also like to help unblocking fixing that as well.

**Comment by stefanv** [comment]
I tried at https://github.com/numpy/numpy/pull/27371, but there was a small change in the test suite Matti didn't like. I'll deal with the outstanding spin issues later today, so we can re-evaluate what to do for NumPy.

**Comment by jarrodmillman** [comment]
Done.
