### ISSUE TITLE
QST: Design behind build command

### ISSUE THREAD

**Issue by lithomas1** [scientific-python/spin#31]
Is there a reason why the build command invokes meson compile/install manually, instead of using pip install and letting projects choose what backend they want to use(with PEP 517)?

This seems pretty finicky, and from my experience also doesn't really work well with conda environments.

**Comment by stefanv** [comment]
`devpy` was originally written to make meson building easier. I don't know if `pip install` gives enough fine-grained control over, e.g., rebuilding, to install the package that way.

With:

```
pip install --no-build-isolation --root=build-install .
```

it looks to me as though it rebuilds each time.

**Comment by lithomas1** [comment]
The way you pass options through pip is through ``--config-settings``

For example, with meson-python as the PEP 517 backend, 
you can do ``--config-settings setup-args="-Ddebug=true`` . (can have compile-args, install-args too)

By the way, out of curiosity, is there a reason why meson is directly invoked here?
(I don't think it's possible to for a Python project to use meson without meson-python, since I don't think meson can build wheels)

**Comment by stefanv** [comment]
As I mentioned, we wrote this specifically to engage with Meson, so that was simply the most obvious route at the time.  I still don't know if I can invoke via pip without rebuilding each time?

Either way: I would be happy to consider build command replacements, as long as they keep working with Meson (since NumPy and a few others rely on it) and don't rebuild.

So, while the above design was organic, another design goal is to make it easy to **replace** the build command with one of your choice.  That said, ideally the default command "does the right thing", so I'd appreciate help in knowing what that would look like.

**Comment by rgommers** [comment]
> pip allows you to pass options through `--config-settings` (can get verbose for multiple config settings though)

As soon as you use `--config-settings`, you are still using the CLI of the underlying build tool. At which point, `pip` is pretty much just a cumbersome intermediate layer that makes your tracebacks and regular stdout output worse, and adds very little.

> So, while the above design was organic, another design goal is to make it easy to **replace** the build command with one of your choice.

This seems like a good thing. Every tool has the same build, install, etc. concepts. And for `devpy` also `test`, `doc` and so on. So it makes sense to me to make the `build` command work with any build system or build backend (e.g. `pip install -e --no-build-isolation --no-deps .` is a reasonable thing to plug in).

> This seems pretty finicky, and from my experience also doesn't really work well with conda environments.

I'm using conda envs on a daily basis, and have no issues. Happy to help if there's a concrete problem.

It's actually an advantage of what `devpy` does here that conda env vs venv vs system Python doesn't matter (it all goes into `build` and `build-install` either way). If you use `pip`, you have to immediately worry about build isolation doing the wrong thing.

**Comment by stefanv** [comment]
Thanks for your input @rgommers; very helpful context.

I think easiest then would be to add alternative built-in build commands for the different types of build systems. I'd need to figure out the interaction between the build command and the test command (test needs different module discovery for `build-install` and in-place installs); with meson's new in-place install functionality, those may be easier to align.

**Comment by lithomas1** [comment]
> As I mentioned, we wrote this specifically to engage with Meson, so that was simply the most obvious route at the time. I still don't know if I can invoke via pip without rebuilding each time?
> 
> Either way: I would be happy to consider build command replacements, as long as they keep working with Meson (since NumPy and a few others rely on it) and don't rebuild.
> 

Ah, I didn't realize numpy was actually using this (thought it used meson-python like scipy. Strangely meson-python is commented out in pyproject.toml?). I'm not familiar with pips internals, but I think doing ``pip install .`` makes it rebuild a wheel to install every time (although the build backend can cache the stuff that goes into a wheel).

> So, while the above design was organic, another design goal is to make it easy to **replace** the build command with one of your choice. That said, ideally the default command "does the right thing", so I'd appreciate help in knowing what that would look like.

I still think that the way the build command is should be re-worked, since it only works out of the box for one build system, so most projects would have to override it. 

(IMO, I think it should be renamed to something like ``build_meson``, to make it clear that it only works with meson). 


> This seems like a good thing. Every tool has the same build, install, etc. concepts. And for `devpy` also `test`, `doc` and so on. So it makes sense to me to make the `build` command work with any build system or build backend (e.g. `pip install -e --no-build-isolation --no-deps .` is a reasonable thing to plug in).

+1 to this. IMO, the most important characteristic of the build command should be that it just works for everyone. Different projects can then configure it if they need it.

numpy will probably need some modifications though, since a pip install is likely to fall back to setuptools.

**Comment by lithomas1** [comment]
> > This seems pretty finicky, and from my experience also doesn't really work well with conda environments.
> 
> I'm using conda envs on a daily basis, and have no issues. Happy to help if there's a concrete problem.

Off topic, but the issue that I had was that a barebones meson install doesn't work out of the box, back when I was still messing with meson instead of meson-python. 

By, the default behavior(prefix) installs stuff in a weird location(C:\Python3{something} or /usr). With ``meson configure '-Dpython.install_env=auto'``, meson seemed to install stuff in my base env, and not the activated env IIRC.

Passing an install dir(configuring python.platlibdir/purelibdir) solves this problem, but feels clunky (I think I was dumping the platlib/purelib paths to a variable and then passing it to meson).

**Comment by rgommers** [comment]
> Ah, I didn't realize numpy was actually using this (thought it used meson-python like scipy. Strangely meson-python is commented out in pyproject.toml?). 

`numpy` is in the middle of a transition from `numpy.distutils` to `meson`/`meson-python`, and we haven't flipped the switch in `pyproject.toml` yet. `devpy` is only used for the Meson build; we have a similar `runtests.py` which is an older, less polished thing that kinda does the same thing as `devpy`.



> I still think that the way the build command is should be re-worked, since it only works out of the box for one build system, so most projects would have to override it.
> 
> (IMO, I think it should be renamed to something like `build_meson`, to make it clear that it only works with meson).

Flipping the default is fine; the `build` command in principle works with every build setup. The only interesting thing is the semantics of it:
1. Invoke the build system, and build and install the package
2. There's a dependency concept here, so if you run `test` without having run `build` before or if the build is out of date, then `build` should be triggered.

> numpy will probably need some modifications though, since a pip install is likely to fall back to setuptools.

No need to worry about a temporary situation with two parallel build systems. The aim should be to make it optimal for the final state.

> By, the default behavior(prefix) installs stuff in a weird location(C:\Python3{something} or /usr). With `meson configure '-Dpython.install_env=auto'`, meson seemed to install stuff in my base env, and not the activated env IIRC.

That sounds like a bug, `auto` is supposed to work - that's explicitly what it is for. Maybe there's an issue with reconfigurating with `meson configure`? I tested the `auto` option when it was introduced, and with `meson setup` in a clean repo it works.

**Comment by eli-schwartz** [comment]
You probably need a native file specifying which python executable to build for -- the meson-python build backend does this automatically.

**Comment by stefanv** [comment]
@lithomas1 In #52 I separate out the Meson build commands. We can now also add commands for `build` (that will likely be build wheel, install wheel, test in the existing env?).

**Comment by rgommers** [comment]
> We can now also add commands for build (that will likely be build wheel, install wheel, test in the existing env?).

I'm not 100% sure what exact commands you're proposing, but I don't think building a wheel should be one. That's not a development activity one needs in regular development. And unlike development activities, the commands to build a regular wheel are standardized (`python -m build` or `pip wheel .`).

**Comment by stefanv** [comment]
I was talking to the astropy folks about how to get fast rebuilds without setup.py, and there doesn't seem to be many options. At first try, the best I found was:

```
python -m build --no-isolation -x -w
```
But that's a wheel build. Do you perhaps know of a better solution?

**Comment by rgommers** [comment]
From https://pip.pypa.io/en/stable/topics/local-project-installs/#build-artifacts: _The project being installed is no longer copied to a temporary directory before invoking the build system, by default._ So that should do the job.

Otherwise just using `setup.py` is also perfectly fine, it hasn't gone anywhere. `build` is the wrong tool, it's focused on providing release artifacts, it doesn't offer a development workflow.

**Comment by stefanv** [comment]
But several projects won't have a `setup.py` file; do you want them to have that file simply so they can run `python setup.py build_ext -i`?

**Comment by stefanv** [comment]
> From https://pip.pypa.io/en/stable/topics/local-project-installs/#build-artifacts: _The project being installed is no longer copied to a temporary directory before invoking the build system, by default._ So that should do the job.

OK, so from that I gather that `pip install -e .` should do the trick if run repeatedly; I'll give it a shot.

**Comment by rgommers** [comment]
Yes, I think so. Should be `pip install -e . --no-isolation` I think.

**Comment by stefanv** [comment]
I tried it with latest `pip` (23.0.1) on astropy, but unfortunately it keeps rebuilding. It could be the way they configure their extensions (https://pypi.org/project/extension-helpers/), but at least in their case the wheel suggestion above rebuilds relatively speedily.  I'll see what happens on other projects.

**Comment by stefanv** [comment]
The scikit-learn documentation has:

> Note
> 
> You will have to run the pip install --no-build-isolation --editable . command every time the > source code of a Cython file is updated (ending in .pyx or .pxd). Use the --no-build-isolation flag to avoid compiling the whole project each time, only the files you have modified. 

So I think we can safely assume that it works for most people. It doesn't on my system, but I'm not sure why :man_shrugging:

**Comment by lithomas1** [comment]
> @lithomas1 In #52 I separate out the Meson build commands. We can now also add commands for `build` (that will likely be build wheel, install wheel, test in the existing env?).

Nice. I noticed in that PR that the meson build commands are still aliased to the ``devpy.build``, ``devpy.test``, etc.

Is the plan to deprecate them so that the PEP 517 equivalent (with pip in editable mode) can be used instead?

**Comment by stefanv** [comment]
> > @lithomas1 In #52 I separate out the Meson build commands. We can now also add commands for `build` (that will likely be build wheel, install wheel, test in the existing env?).
> 
> Nice. I noticed in that PR that the meson build commands are still aliased to the `devpy.build`, `devpy.test`, etc.
> 
> Is the plan to deprecate them so that the PEP 517 equivalent (with pip in editable mode) can be used instead?

Those aliases are there for backward compatibility. All the docs have been updated to specify them explicitly, so you have, e.g., `devpy.cmds.meson.build`. Then we can add something like `devpy.cmds.setuptools.build`.

**Comment by stefanv** [comment]
This discussion seems to have concluded. If there are specific requests for `setup.py` or pip commands, please file issues accordingly and we'll get those implemented.
