### ISSUE TITLE
Test command behavior needed for NumPy's use of devpy

### ISSUE THREAD

**Issue by rgommers** [scientific-python/spin#40]
@stefanv as a follow up to our chat today and to gh-13 (which covered multiple things), here are the issues with the `test` command I ran into for NumPy:

- The default for NumPy should be to run the `'fast'` tests, not `'full'`. I.e, the equivalent of `np.test()`.
- The `test` command on NumPy should not invoke `pytest` directly, but invoke `PytestTester` from `numpy/_pytesttester.py` - that will solve a bunch of things, including the `fast` mode mentioned above.
- Being able to run per-submodule tests is very useful. And a few other things as well that SciPy's `dev.py` has. All the following apply for NumPy unchanged (I left out `--coverage`, that's too niche I'd say):
```
--verbose    -v             more verbosity    
--parallel   -j  N_JOBS     Number of parallel jobs for testing            
--durations  -d  NUM_TESTS  Show timing for the given number of slowest tests 

--submodule  -s  MODULE_NAME  Submodule whose tests to run (cluster, constants, ...) 
--tests      -t  TESTS        Specify tests to run
--mode       -m  MODE         'fast', 'full', or something that could be passed to pytest -m
                              as a marker expression   
                              [default: fast]
```

- It's also quite useful to get the `test` command to trigger the `build` command by default, to avoid having to do so manually or running the tests without picking up the latest local changes a user has.

**Comment by mattip** [comment]
One more thing I noticed when trying to run the tests under a debugger: since devpy starts a new process, I cannot do `gdb --args python dev.py test ...`. If this is a requirement of the way `devpy` loads numpy from `build-install/...`, there should be a way to add a debugging mode.

**Comment by mattip** [comment]
> It's also quite useful to get the test command to trigger the build command by default

meson-python has support for [editable installs](https://meson-python.readthedocs.io/en/latest/how-to-guides/editable-installs.html#editable-installs), maybe devpy could take something from there?

**Comment by rgommers** [comment]
Editable installs are still in early testing, and we still have to wait and see whether they get on par with the approach in devpy.

**Comment by WarrenWeckesser** [comment]
In the meantime, here are some notes on pytest arguments that can be used to fine-tune `spin test` and replicate some of the options in `dev.py`.

* To use more than one CPU to run the tests:

      spin test -- -n NUM_CPUS

  E.g.

      spin test -- -n 8

  For more details, see https://pytest-xdist.readthedocs.io/en/latest/distribution.html

* To run the tests for a specific submodule:

      spin test -- --pyargs FULLY_QUALIFIED_MODULE_NAME

  E.g.

      spin test -- --pyargs numpy.random

* To get a report of the durations of the N slowest tests:

      spin test -- --durations=N

  E.g.

      spin test -- --durations=10

* To specify a pattern that the name of the test must match:

      spin test -- -k PATTERN

  E.g.

      spin test -- -k "geometric"
      spin test -- -k "geometric and not rgeometric"

  See https://docs.pytest.org/en/7.3.x/reference/reference.html#command-line-flags

**Comment by stefanv** [comment]
> One more thing I noticed when trying to run the tests under a debugger: since devpy starts a new process, I cannot do `gdb --args python dev.py test ...`. If this is a requirement of the way `devpy` loads numpy from `build-install/...`, there should be a way to add a debugging mode.

@mattip Quick question: are you running on Windows? If so, that may be a problem since, as far as I can tell, there is no easy way of spawning processes on that platform that replace the current one.

Now that editable builds work, that may be an easier way to achieve the same.

**Comment by stefanv** [comment]
> spin test -- -k "geometric"
> spin test -- -k "geometric and not rgeometric"

@WarrenWeckesser I thought this was a neat primer, so I added it to the docstring for `test`. Thanks!

**Comment by stefanv** [comment]
> @stefanv as a follow up to our chat today and to [gh-13](https://github.com/scientific-python/spin/issues/13) (which covered multiple things), here are the issues with the `test` command I ran into for NumPy:
> 
>     * The default for NumPy should be to run the `'fast'` tests, not `'full'`. I.e, the equivalent of `np.test()`.
> 
>     * The `test` command on NumPy should not invoke `pytest` directly, but invoke `PytestTester` from `numpy/_pytesttester.py` - that will solve a bunch of things, including the `fast` mode mentioned above.
> 
>     * Being able to run per-submodule tests is very useful. And a few other things as well that SciPy's `dev.py` has. All the following apply for NumPy unchanged (I left out `--coverage`, that's too niche I'd say):
> 
> 
> ```
> --verbose    -v             more verbosity    
> --parallel   -j  N_JOBS     Number of parallel jobs for testing            
> --durations  -d  NUM_TESTS  Show timing for the given number of slowest tests 
> 
> --submodule  -s  MODULE_NAME  Submodule whose tests to run (cluster, constants, ...) 
> --tests      -t  TESTS        Specify tests to run
> --mode       -m  MODE         'fast', 'full', or something that could be passed to pytest -m
>                               as a marker expression   
>                               [default: fast]
> ```
> 
>     * It's also quite useful to get the `test` command to trigger the `build` command by default, to avoid having to do so manually or running the tests without picking up the latest local changes a user has.

Now that the build is triggered when the tests are run, and having added Warren's documentation, the only feature above that is missing (i.e., that cannot easily be set as a pytest flag, and is enabled by default) is `-m fast`. I have an idea of how to handle that for numpy, and will submit a PR soon.

**Comment by stefanv** [comment]
(We can pull in those other flags too, for ease of use and consistency over projects, I just want to get the functionality in place as a start.)

**Comment by mattip** [comment]
> Quick question: are you running on Windows?

No, I was debugging in linux. I think spin does this differently now, it seems to work. I do need to use `gdb --args python -m spin python -- -c "import numpy as np; <test code>"` since `spin` is  a script, not an executable.

**Comment by stefanv** [comment]
> > Quick question: are you running on Windows?
> 
> No, I was debugging in linux. I think spin does this differently now, it seems to work. I do need to use `gdb --args python -m spin python -- -c "import numpy as np; <test code>"` since `spin` is a script, not an executable.

I've also added a run command (will add that to my numpy patch), so that you can do the following (with Python `>=3.11`):

```
alias debug='gdb --args python -m spin run python -P -c'
debug 'import numpy as np; np.linalg.norm(123)'
```

**Comment by stefanv** [comment]
OK, I think we're close with https://github.com/numpy/numpy/pull/24083#issuecomment-1616021737

Of the flags mentioned in the issue description, this implents `-j` and `-m` (with defaults), which should improve the default experience quite a bit.

**Comment by stefanv** [comment]
Most of this functionality is now covered, either in spin or numpy itself. I'll close, but please feel free to file new issues for specific missing functionality.
