### ISSUE TITLE
DEV: Can `pydevtool.cli` be used to create a unified context?

### ISSUE THREAD

**Issue by ganesh-k13** [scientific-python/spin#45]
Scipy [uses `pydevtool.cli`](https://github.com/scipy/scipy/blob/main/dev.py#L130) that helps in bunching the common commands like [`build-dir`](https://github.com/scipy/scipy/blob/main/dev.py#L231-L244). As of today in this repo, we are repeating `build-dir` in every command and lack a few utility commands to infer/set python paths from these common args.

I'd be happy to bunch it and refactor all the commands into a subclass of [`Task`](https://github.com/pydoit/pydevtool/blob/c0e8c7cfe46b34420fcce46cd3cda295b7433a6a/src/pydevtool/cli.py#L206) and add common inferencing functions like [`Dirs`](https://github.com/scipy/scipy/blob/9d74b29239d05f6ec63e4c16cd8a49d0fa58e7c2/dev.py#L283-L338) but wanted to confirm if this is the right way forward or the project maintainers had something else in mind.

**Comment by stefanv** [comment]
For devpy, the design is intended to be as simple as possible, and to only use dependencies if truly necessary.

We'd have to see how it would compare to implement this outside pydevtool.cli, and also to ask whether the increased complexity is worth it.

**Comment by ganesh-k13** [comment]
Ah ok, that makes sense. I was working on `bench` and had to use a small portion of `build` command and wanted to clarify this. I think I'll stick with what's there today.

**Comment by rgommers** [comment]
After working on some NumPy code again today, I wasted bunch of time scratching my head why `./dev.py test` was still failing when I thought I had fixed something. The lack of dependencies requires typing:
```
./dev.py build && ./dev.py test
```
all the time. I think the gap in usability is pretty large.

**Comment by rgommers** [comment]
So far I've been waiting for (2). I think dependencies are necessary though when working on a numpy/scipy-sized code base, and it's hard to use devpy for numpy development right now. _However_, for smaller projects where (a) editing compiled code is rare and (b) that doesn't use Meson, `devpy` could rely on editable installs and then explicit dependencies between tasks may not be needed (pure Python edits get reflected immediately). In that case, we should do (1) for NumPy.

What do you think?

**Comment by stefanv** [comment]
Are you happy to call the build command each time before testing, or do you want it to be smart about detecting when a build is necessary? I think the first scenario I can complete without much difficulty.

**Comment by rgommers** [comment]
There's no need to be smart - a do-nothing rebuild takes only about 100 ms. Also, any commit updates at least the version number when that includes a git hash, so a rebuild is very often needed and checking that is difficult.

**Comment by stefanv** [comment]
OK, cool, I'll get this added later today (sorry for the wasted time, that is never good!). I was trying to figure out how one would pass options through to the build via the test command, but I see SciPy's dev.py doesn't allow for that either. You have to run the dedicated build command if you want to specify flags like `--gcov`, but the `test` command itself just invokes a basic build.

**Comment by rgommers** [comment]
No worries. And yes, it's nothing too complicated.

**Comment by stefanv** [comment]
Please see https://github.com/scientific-python/devpy/pull/51

**Comment by ganesh-k13** [comment]
I think it makes sense for simplicity but I hope we don't repeat what we have at SciPy. In reference to dependencies, Task object provides [task_dep](https://github.com/scipy/scipy/blob/main/dev.py#L780) that does a topo sort of dependencies.

**Comment by stefanv** [comment]
Can you explain what "I hope we don't repeat what we have at SciPy" means?

In terms of dependencies: do we really need a topo sort, and when would that be useful?

**Comment by ganesh-k13** [comment]
Hi sorry for the delay. I think as of now we don't have any complex dependencies and can keep it simple. As for repeating SciPy features, lets leverage [pydevtool.cli](https://github.com/scipy/scipy/blob/main/dev.py#L130) if the requirement arises.

**Comment by stefanv** [comment]
Some targets (`test` and `docs` specifically), now compile before executing.
I have not added this to `run` or any of the shell commands, since it's not as clear that you want to trigger a build before running them. E.g., you may want to try a few things on the currently built version, before building with modifications.

Either way, there's a pattern that can be extended.

I'll close this for now; feel free to open a new issue if it comes up again.
