### ISSUE TITLE
Run a command in the shell without invoking the shell

### ISSUE THREAD

**Issue by adam2392** [scientific-python/spin#69]
Hi,

I'm currently using meson-python to build a package locally and also do development. However, beyond just running unit-tests, I would also like to run certain Python files (e.g. example scripts) and test them out locally. 

The current workflow I have is:

1. build and install `Dev.py build -j 4`
2. launch a shell `dev.py shell`
3. add the build to the PATH
4. Run Python stuff inside

This is kinda tedious because it just involves a bunch of commands occurring in different shells technically. I was wondering if it is possible to implement something like:

`./dev.py run <shell command>`

E.g. `./dev.py run ./example.py` which runs `example.py` file inside the shell.

Note this is very similar to what for example poetry has with `poetry run <shell command>`.

**Comment by stefanv** [comment]
Hi @adam2392 :wave: 

Note that `dev.py` had to be renamed to `spin` due to a naming conflict on `pypi`.

I'd like to understand your use-case better. Have you tried something like:

```
$ spin shell -- -c ls
```

?

**Comment by adam2392** [comment]
Hi @stefanv thanks for the quick response. It looks like someone had already proposed the switch in our package: https://github.com/neurodata/scikit-tree/pull/54

Sweet that does work I think for certain commands like `ls`, but not Python scripts?

However, I have to run Python scripts, so I get the following error:

```
sudo spin shell -- -c ./examples/plot_iris_dtc.py
💻 Launching shell with PYTHONPATH="/Users/adam2392/Documents/scikit-tree/build-install/usr/lib/python3.9/site-packages"
⚠  Change directory to avoid importing source instead of built package
⚠  Ensure that your ~/.shellrc does not unset PYTHONPATH
$ /bin/sh -c ./examples/plot_iris_dtc.py
/bin/sh: ./examples/plot_iris_dtc.py: Permission denied
```

**Comment by stefanv** [comment]
Is that file executable? If not, you can do `-c python filename.py`.

On Python 3.11, you can also do `spin python filename.py`.

On older versions of Python, you can run try: `spin ipython filename.py`.  We should probably look into a better workaround for older Python versions, but Python 3.11 will soon be mainstream :)

**Comment by stefanv** [comment]
Thanks for the feedback @adam2392 and @rgommers. Please see #70.
