### ISSUE TITLE
Add spin benchmark to run a comparison of HEAD to main using asv

### ISSUE THREAD

**Issue by mattip** [scientific-python/spin#71]
Add the ability to replace `runtests.py --bench-compare`. I always forget how to do this.

**Comment by mattip** [comment]
this would also be faster if it could use meson to build the numpy versions rather than setuptools

**Comment by stefanv** [comment]
Is this a standard operation across projects? If not, I'm happy to also just write a command for NumPy.

**Comment by mattip** [comment]
I think scipy uses asv as well, and other projects might too if it was convenient.

**Comment by rgommers** [comment]
I think it doesn't require `asv`. It's fair to assume that projects have or may want a benchmark suite. A standard command should be `spin bench` imho. If you look at SciPy's `dev.py`, it allows further specialization, like:

- `dev.py bench --compare <commit-sha>`
- `dev.py bench --tests <asv selector expression>`
- `dev.py bench -s cluster`

So `bench` pretty much mirrors `test` with the submodule and tests selection, and then `--compare` is specific to benchmarking. `spin` could do the same, defaulting to `asv` but not precluding using another benchmarking framework (if it doesn't have `--compare` functionality, that'd be no big deal then).

**Comment by stefanv** [comment]
Right, it's always easy to override a command or create a new one.

Here's what we use in skimage, which doesn't have any fancy options:

https://github.com/scikit-image/scikit-image/blob/main/.spin/cmds.py#L37

**Comment by mattip** [comment]
Ahh, cool. I didn't know about [custom commands](https://github.com/scientific-python/spin#-custom-commands).
