### ISSUE TITLE
Add option `noplot` to `docs` command of spin

### ISSUE THREAD

**Issue by adam2392** [scientific-python/spin#95]
It would be great to have the option to not plot sphinx output in the `meson.docs` command. 

Happy to submit a PR if this is acceptable.

**Comment by stefanv** [comment]
Do you mean silencing the `docs` command? That'd be totally fine as an option, and we should add it to other commands as well.

That flag will need to be passed to all `run_` commands being used in the command, as the `output` flag.

**Comment by adam2392** [comment]
No moreso passing extra arguments to the docs command. 

Sphinx has a make html and also make html-noplot which doesn't render or run any sphinx gallery examples. This is useful for quick docs debugging.

**Comment by stefanv** [comment]
It comes from [sphinx-gallery](https://sphinx-gallery.github.io/stable/configuration.html#building-without-executing-examples):

```
    $(SPHINXBUILD) -D plot_gallery=0 -b html $(ALLSPHINXOPTS) $(SOURCEDIR) $(BUILDDIR)/html
```

**Comment by stefanv** [comment]
We can invoke SPHINXBUILD directly, potentially, and then any optional arguments such as `plot_gallery=0` can be passed on through, or we can add a flag for it.

**Comment by stefanv** [comment]
Would this work for you?

https://github.com/scientific-python/spin/pull/111
