### ISSUE TITLE
Emojis not showing up on zsh/linux

### ISSUE THREAD

**Issue by melissawm** [scientific-python/spin#98]
Maybe there is a missing dependency I don't have installed as this is a fresh install of Manjaro.

Here's what the help command output looks like. Only two of the emojis are correctly rendered.

Let me know if you need more information.

![Screenshot_20230811_173032](https://github.com/scientific-python/spin/assets/3949932/745c9eda-a923-4f08-b44d-242aa2e027dd)

**Comment by stefanv** [comment]
Oh, no, this is terrible. What is your locale?

**Comment by melissawm** [comment]
```
LANG=pt_BR.UTF-8
LC_CTYPE="pt_BR.UTF-8"
LC_NUMERIC=pt_BR.UTF-8
LC_TIME=pt_BR.UTF-8
LC_COLLATE="pt_BR.UTF-8"
LC_MONETARY=pt_BR.UTF-8
LC_MESSAGES="pt_BR.UTF-8"
LC_PAPER=pt_BR.UTF-8
LC_NAME=pt_BR.UTF-8
LC_ADDRESS=pt_BR.UTF-8
LC_TELEPHONE=pt_BR.UTF-8
LC_MEASUREMENT=pt_BR.UTF-8
LC_IDENTIFICATION=pt_BR.UTF-8
LC_ALL=
```

**Comment by bsipocz** [comment]
Unrelated to spin, but I keep seeing non-rendered emojis on the website, too. (Used to be https://github.com/scientific-python/scientific-python.org/issues/75 which was worked around by removing emojis, but I keep seeing it on the learn site)

**Comment by stefanv** [comment]
@melissawm I don't think it's locale related after all; the terminal font you have seem not to be have the emoji characters.

Can you try:

```
sudo pacman -S noto-fonts-emoji
fc-cache -f -v
```

and then restart your terminal?

**Comment by melissawm** [comment]
oh that did solve it, thanks! Want me to add a note to the README with these instructions?

**Comment by stefanv** [comment]
Yay! Yes please that'd be great.

**Comment by melissawm** [comment]
Sorry I dropped the ball on this, thanks for doing it !
